version: '3.10'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=blibdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - C:\Users\1ms21\OneDrive\Desktop\Learning\barham-books-master\barham-books-master:/code
    ports:
      - "8000:8000"
    depends_on:
      - db