# Generated by Django 5.0.1 on 2024-01-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_book_year'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='original publication year'),
        ),
        migrations.AlterField(
            model_name='booktags',
            name='slug',
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='taggedbook',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
